# Generated by Django 3.2 on 2026-01-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HMSMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillNumber', models.CharField(max_length=50)),
                ('BillType', models.CharField(max_length=50)),
                ('BillDate', models.DateTimeField()),
                ('SubTestcode', models.CharField(blank=True, max_length=50, null=True)),
                ('SubTestName', models.CharField(blank=True, max_length=500, null=True)),
                ('SerialNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('mobilenumber', models.CharField(max_length=25)),
                ('IPOPType', models.CharField(max_length=20)),
                ('IPOPNumber', models.CharField(max_length=50)),
                ('PatientTitle', models.CharField(max_length=10)),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientAge', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('RefDoctor', models.CharField(max_length=100)),
                ('TestCode', models.CharField(max_length=50)),
                ('TestName', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billnumber', models.CharField(max_length=100)),
                ('testcode', models.CharField(max_length=100)),
                ('subtestcode', models.CharField(max_length=100)),
                ('resultvalue', models.CharField(max_length=500)),
                ('resultdate', models.CharField(blank=True, max_length=50, null=True)),
                ('resulttime', models.CharField(blank=True, max_length=50, null=True)),
                ('billtype', models.CharField(blank=True, max_length=100, null=True)),
                ('serialnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('opnumber', models.CharField(blank=True, max_length=100, null=True)),
                ('patientname', models.CharField(blank=True, max_length=255, null=True)),
                ('patientage', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('api_response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
