# Generated by Django 3.2 on 2026-01-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_machineautomationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateHMSMILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('test_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('request_data', models.TextField(blank=True, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
