# Generated by Django 3.2 on 2026-05-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_createhmsmilog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEntryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill_number', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=255)),
                ('template_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ManualTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('test_code', models.CharField(max_length=100)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('parameters', models.JSONField(default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateHMSMILog',
        ),
        migrations.AlterField(
            model_name='hmsmi',
            name='PatientTitle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
