# Generated by Django 3.2 on 2026-05-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_auto_20260509_0710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualTemplate',
        ),
        migrations.RemoveField(
            model_name='manualentrylog',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='manualentrylog',
            name='template_name',
        ),
        migrations.AddField(
            model_name='manualentrylog',
            name='response_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
