# Generated by Django 3.2 on 2026-05-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_auto_20260509_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualentrylog',
            name='test_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
